[package]
name = "gennaro-dkg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64-url = "1.3"
rand_core = { version = "0.6", features = ["std"] }
thiserror = "1.0"
elliptic-curve = "0.12"
serde = "1"
uint-zigzag = { version = "0.2", features = ["std"] }
vsss-rs = { version = "2.3.2", features = ["std"] }
