[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography"]
description = "The Gennaro Distributed Key Generation Algorithm"
documentation = "https://docs.rs/gennaro-dkg"
edition = "2021"
homepage = "https://github.com/mikelodder7/gennaro-dkg"
license = "Apache-2.0 OR MIT"
name = "gennaro-dkg"
readme = "README.md"
repository = "https://github.com/mikelodder7/gennaro-dkg"
version = "0.2.1"

[dependencies]
anyhow = "1.0.68"
base64-url = "1.4.13"
log = "0.4.17"
rand_core = { version = "0.6.4", features = ["std"] }
rand_chacha = "0.3.1"
thiserror = "1.0.38"
elliptic-curve = "0.12.3"
serde = "1.0"
uint-zigzag = { version = "0.2.1", features = ["std"] }
vsss-rs = { version = "2.3.2", features = ["std"] }

[dev-dependencies]
bls12_381_plus = "0.5.5"
k256 = "0.11"
p256 = "0.11"
maplit = "1.0"
serde_json = "1.0"
