[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography"]
description = "The Gennaro Distributed Key Generation Algorithm"
documentation = "https://docs.rs/gennaro-dkg"
edition = "2021"
homepage = "https://github.com/mikelodder7/gennaro-dkg"
license = "Apache-2.0 OR MIT"
name = "gennaro-dkg"
readme = "README.md"
repository = "https://github.com/mikelodder7/gennaro-dkg"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
base64-url = "1.3"
rand_core = { version = "0.6", features = ["std"] }
rand_chacha = "0.3"
thiserror = "1.0"
elliptic-curve = "0.12"
serde = "1"
uint-zigzag = { version = "0.2", features = ["std"] }
vsss-rs = { version = "2.3.2", features = ["std"] }

[dev-dependencies]
bls12_381_plus = "0.5.5"
k256 = "0.11"
p256 = "0.11"
maplit = "1.0"
serde_json = "1.0"
